docs: improve Edge connectivity docs
igraph/rigraph pull request #1119
Opened 2024-01-16 08:57 UTC by maelle

Fix #960

2024-01-17 14:08 UTC, szhorvat requested changes
I'd suggest the corrections I indicated. Other than that it looks good!

2024-01-17 14:08 UTC, szhorvat commented on R/flow.R
> +#'  eliminate all paths paths from `source` to `target`.
```suggestion
#' a graph is the minimum number of vertices that must be deleted to
#'  eliminate all (directed) paths from `source` to `target`.
```

2024-01-17 14:08 UTC, szhorvat commented on R/flow.R
> +#' contributes one extra path.
```suggestion
#' When there are no direct edges between the source and the target, the number
#' of vertex-disjoint paths is the same as the vertex connectivity of
#' the two vertices. When some edges are present, each one of them
#' contributes one extra path.
```

2024-01-22 15:08 UTC, maelle commented
@szhorvat I'm sorry but I can't merge with Aviator if you don't review this again. :pray:

2024-01-23 12:08 UTC, merged

2024-01-23 12:08 UTC, krlmlr commented
Let's open a new PR if this needs more changes.

2024-01-23 12:17 UTC, szhorvat commented
I'm sorry, I didn't notice this! Good that it's now merged.