feat: `simple_cycles()` lists all simple cycles
igraph/rigraph pull request #1580
Opened 2024-11-11 11:35 UTC by szhorvat

This PR depends on #1567 and #1571. For now, it targets the `simple_cycles-base-branch` branch, which has those PRs merged. Once they are merged to `main`, it should be marked as ready-for-review and re-targeted.

Can you please help me implement tests @maelle ? What I'd like to have a is a check on the cycle length histograms for the graph already added to the examples. Count cycles of length 1, length 2, etc. and add a check on the expected numbers. I'm not sure what's the best way to do this in R.

2024-11-11 12:59 UTC, szhorvat commented
Perhaps `min` / `max` should use a `NULL` default instead of `-1`.

We can model this on `cliques()`

2024-11-28 10:10 UTC, maelle commented
@krlmlr why is a review by @Antonov548 needed? After that review, I can work on the tests.

2024-11-28 10:12 UTC, Antonov548 commented
> @krlmlr why is a review by @Antonov548 needed? After that review, I can work on the tests.

The idea was just to take a look active pull requests to still keep up to date what is changing.

2025-01-05 19:43 UTC, krlmlr requested changes
Thanks. The "simple cycles" feature is the first commit in the C core that breaks the R package. Almost ready to tackle it.

2025-01-05 19:43 UTC, krlmlr commented on R/aaa-auto.R
> -simple_cycles_impl <- function(graph, mode=c("out", "in", "all", "total"), min.cycle.length=-1, max.cycle.length=-1) {
Do you see a downside in keeping this and making `simple_cycles()` a wrapper of this function?

2025-04-04 15:22 UTC, szhorvat commented on R/aaa-auto.R
> -simple_cycles_impl <- function(graph, mode=c("out", "in", "all", "total"), min.cycle.length=-1, max.cycle.length=-1) {
Downsides are that the `mode <- ` lines must be repeated in the wrapper and we still need to add the `is.null()` checks. Overall, it won't be a simpler solution.

That said I have no strong preference.

2025-04-04 15:23 UTC, szhorvat commented
@krlmlr @schochastics This is now rebased on `main`. Can someone please help add tests for this, and review the existing code? Would be nice to get this feature in, as it's basically done.

2025-04-04 15:40 UTC, schochastics commented
I will add tests

2025-04-04 19:06 UTC, schochastics commented
I added tests and tweaked the style a little.

2025-04-04 19:53 UTC, szhorvat commented on tests/testthat/test-cycles.R
> +  g <- graph_from_literal(A - +B - +C - +A - +D - +E + -F - +A, E - +E, A - +F, simplify = FALSE)
Literals are weird again :-((

2025-04-04 20:25 UTC, schochastics commented on tests/testthat/test-cycles.R
> +  g <- graph_from_literal(A - +B - +C - +A - +D - +E + -F - +A, E - +E, A - +F, simplify = FALSE)
ah damn that was my mistake

2025-04-10 10:22 UTC, szhorvat commented
@krlmlr Isn't the `mode <- switch ...` still necessary?

2025-04-10 12:19 UTC, merged

2025-04-10 12:19 UTC, krlmlr commented
Thanks!