Use testthat edition 3
igraph/rigraph pull request #576
Opened 2022-09-23 16:22 UTC by krlmlr

for parallel testing.

Starts with consistent code formatting (removal of spaces at EOF and lines at EOL), a prerequisite for the following bulk search+replace operations.

Adapts the test code to be compatible with testthat edition 3, which is required for parallel testing. This reduces the time to test the entire package to a half (4 cores, 32s -> ~16s).

A lot of files are touched, each commit can be reviewed individually. I can submit smaller PRs if needed.

2022-09-23 19:25 UTC, ntamas commented
@krlmlr I have merged #577 and now there are several files that are in conflict with `dev`. I tried resolving these with `git merge -Xours dev` but I cannot push new commits to this PR. Can you please either allow us to push commits to this PR or resolve the conflicts so I can proceed with the review?

2022-09-23 19:30 UTC, ntamas requested changes
Thanks a lot, everything looks good apart from the two lines that I pointed out. If you manage to fix the merge conflicts and these two issues then I think this can safely be merged.

Re whitespace: should we add a pre-commit hook that ensures that there are no trailing whitespace anywhere? In Python projects I would use https://pre-commit.com/ but I don't know whether there's a similar tool for R projects.

2022-09-23 19:57 UTC, krlmlr commented
Thanks, good catch. Resolved. I wonder why my local test runs didn't catch the problem.

2022-09-23 20:44 UTC, ntamas commented
The CI failure is weird, I cannot reproduce it locally on my Mac. I'm gonna re-run the failed job and see what happens.

2022-09-23 20:51 UTC, krlmlr commented
I’ll take a look too. 

> Am 23.09.2022 um 22:44 schrieb Tamás Nepusz ***@***.***>:
> 
> ﻿
> The CI failure is weird, I cannot reproduce it locally on my Mac. I'm gonna re-run the failed job and see what happens.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2022-09-23 21:55 UTC, ntamas commented
All checks passed so I'm going to merge this, thanks!

2022-09-23 21:55 UTC, merged

2022-09-24 03:59 UTC, krlmlr commented
Thanks. Some notes:

- Confirming that the `Matrix::sparseMatrix::Matrix` error leads to a parse error that is silently skipped when running tests in parallel. This is the reason why I didn't see the error, but it's great these errors are caught in CI/CD.
- With parallel testing, I'm now seeing sporadic test failures and warnings:
    - in `test-vs-es:230`, almost always
    - in `test_leading.eigenvector.community.R:65:5`, warning or error, rarely: ARPACK solver failed to converge (1001 iterations, 0/1 eigenvectors converged). Can be reproduced independently by running `testthat::test_local("leading.eigenvector.community")` repeatedly
    
    Submitted PRs.

2022-09-24 18:13 UTC, ntamas commented
When you mention "parallel testing", does it mean that `testthat` is running multiple _threads_ in the same process, and those threads are calling igraph functions concurrently, or does it use multiple _processes_? Is there anything special I need to do to turn on parallel testing on my machine or is it now enabled by default?

2022-09-24 18:16 UTC, krlmlr commented
Tests are run in parallel processes, as R is single-threaded. It is enabled by a setting in `DESCRIPTION` that starts with `Config/testthat/...`. Control the number of processes with the `TESTTHAT_CPUS` environment variable.