feat!: change "incidence matrix" naming to "biadjacency matrix"
igraph/rigraph pull request #962
Opened 2023-11-13 13:43 UTC by maelle

Fix  #900

2023-11-13 13:44 UTC, maelle commented
This becomes a small blocker for #716 since it edits the zzz-deprecate.R script.

2023-11-13 13:46 UTC, maelle commented on R/conversion.R
> +   lifecycle::deprecate_soft("1.5.2", "as_incidence_matrix()", "as_biadjacency_matrix()")
@krlmlr what version number should we use here?

2023-11-13 13:46 UTC, krlmlr approved these changes

2023-11-13 14:26 UTC, szhorvat requested changes
Can you please update the documentation text to refer to "bipartite adjacency matrix" instead of "incidence matrix" in all places? Add just one note along these lines:

> Some authors refer to the bipartite adjacency matrix as the "bipartite incidence matrix". igraph 1.6.0 and later does not use this naming to avoid confusion with the edge-vertex incidence matrix.

2023-11-13 17:06 UTC, krlmlr commented
@szhorvat: Please remove the "blocked" label when good.

2023-11-13 17:18 UTC, szhorvat commented
@krlmlr Looks good to me, but are you going to do 1.5.2 instead of 1.6.0? There are a lot of changes here, worth a version bump ...

2023-11-13 17:31 UTC, szhorvat commented
The version numbers in this PR are all 1.5.2, and @maelle was asking about about what version number you were going to use.

2023-11-13 22:51 UTC, szhorvat approved these changes

2023-11-13 22:52 UTC, szhorvat commented
@krlmlr This looks fine for me, other than the version. I'll leave it to you to deal with what version is mentioned in the docs.

2023-11-18 06:36 UTC, krlmlr commented
Thanks! This PR doesn't seem to be breaking anything.

2023-11-18 10:05 UTC, krlmlr commented
@maelle: Can you please work on the test coverage? Probably it's sufficient to test that the deprecated variants give the same results as the original, plus a deprecation warning?

2023-11-20 10:56 UTC, krlmlr approved these changes
Thanks, looks good! Can you please set the "mergequeue" label when done?

2023-11-20 10:56 UTC, krlmlr commented on src/cpp11.cpp
> +extern SEXP R_igraph_add_edges(SEXP, SEXP);
Can you please revert changes to this file?

2023-11-21 05:03 UTC, krlmlr commented
Thanks!

2023-11-21 05:33 UTC, merged